name: Build and publish BLE library
on:
  push:
    branches:
      - master
      - hotfix/*

jobs:
  library:
    name: Build and publish ble library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          scope: '@iotinga'

      - name: Config git
        run: |
          git config --global user.name iotinga-devops
          git config --global user.email devops@iotinga.it

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Bump version
        run: npm version --no-git-tag-version ${{ steps.version.outputs.new_tag }}

      - name: Commit new version
        continue-on-error: true
        run: git commit -am "[CI] bump version to $IOTINGA_VERSION" && git push

      - name: Install dependencies
        run: npm ci

      - name: Publish npm package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@iotinga'

      - name: Publish npm package (on private registry)
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
